spring.datasource.url= jdbc:mysql://database-1.chm2qow8ip2t.ap-south-1.rds.amazonaws.com:3306/testdb?useSSL=false
spring.datasource.username= admin
spring.datasource.password= purple123

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update